
export enum OnEventParam {
	base,
	die,
	championKillPre,
	damage,
	goldSpent,
	goldEarned,
	itemConsumedPurchased,
	damageCriticalStrike,
	minionKill,
	heal,
	buff,
	cc,
	killingSpree,
	assist,
	itemSoldOrRemoved,
	itemUndo,
	itemCallout,
	itemChange,
	undoEnabledChange,
	shopItemSubstitutionChange,
	globalMessageGeneric,
	alert,
	capturePoint,
}

export enum OnEvent {
	onDelete = 0x00,
	onSpawn = 0x01,
	onDie = 0x02,
	onKill = 0x03,
	onChampionDie = 0x04,
	onChampionKillPre = 0x05,
	onChampionKill = 0x06,
	onChampionKillPost = 0x07,
	onChampionSingleKill = 0x08,
	onChampionDoubleKill = 0x09,
	onChampionTripleKill = 0x0A,
	onChampionQuadraKill = 0x0B,
	onChampionPentaKill = 0x0C,
	onChampionUnrealKill = 0x0D,
	onFirstBlood = 0x0E,
	onDamageTaken = 0x0F,
	onDamageGiven = 0x10,
	onSpellCast1 = 0x11,
	onSpellCast2 = 0x12,
	onSpellCast3 = 0x13,
	onSpellCast4 = 0x14,
	onSpellAvatarCast1 = 0x15,
	onSpellAvatarCast2 = 0x16,
	onGoldSpent = 0x17,
	onGoldEarned = 0x18,
	onItemConsumeablePurchased = 0x19,
	onCriticalStrike = 0x1A,
	onAce = 0x1B,
	onReincarnate = 0x1C,
	onChangeChampion = 0x1D,
	onDampenerKill = 0x1E,
	onDampenerDie = 0x1F,
	onDampenerRespawnSoon = 0x20,
	onDampenerRespawn = 0x21,
	onDampenerDamage = 0x22,
	onTurretKill = 0x23,
	onTurretDie = 0x24,
	onTurretDamage = 0x25,
	onMinionKill = 0x26,
	onMinionDenied = 0x27,
	onNeutralMinionKill = 0x28,
	onSuperMonsterKill = 0x29,
	onAcquireRedBuffFromNeutral = 0x2A,
	onAcquireBlueBuffFromNeutral = 0x2B,
	onHqKill = 0x2C,
	onHqDie = 0x2D,
	onHeal = 0x2E,
	onCastHeal = 0x2F,
	onBuff = 0x30,
	onCrowdControlDealt = 0x31,
	onKillingSpree = 0x32,
	onKillingSpreeSet1 = 0x33,
	onKillingSpreeSet2 = 0x34,
	onKillingSpreeSet3 = 0x35,
	onKillingSpreeSet4 = 0x36,
	onKillingSpreeSet5 = 0x37,
	onKillingSpreeSet6 = 0x38,
	onKilledUnitOnKillingSpree = 0x39,
	onKilledUnitOnKillingSpreeSet1 = 0x3A,
	onKilledUnitOnKillingSpreeSet2 = 0x3B,
	onKilledUnitOnKillingSpreeSet3 = 0x3C,
	onKilledUnitOnKillingSpreeSet4 = 0x3D,
	onKilledUnitOnKillingSpreeSet5 = 0x3E,
	onKilledUnitOnKillingSpreeSet6 = 0x3F,
	onKilledUnitOnKillingSpreeDoubleKill = 0x40,
	onKilledUnitOnKillingSpreeTripleKill = 0x41,
	onKilledUnitOnKillingSpreeQuadraKill = 0x42,
	onKilledUnitOnKillingSpreePentaKill = 0x43,
	onKilledUnitOnKillingSpreeUnrealKill = 0x44,
	onDeathAssist = 0x45,
	onQuit = 0x46,
	onLeave = 0x47,
	onReconnect = 0x48,
	onGameStart = 0x49,
	onAssistingSpreeSet1 = 0x4A,
	onAssistingSpreeSet2 = 0x4B,
	onChampionTripleAssist = 0x4C,
	onChampionPentaAssist = 0x4D,
	onPing = 0x4E,
	onPingPlayer = 0x4F,
	onPingBuilding = 0x50,
	onPingOther = 0x51,
	onEndGame = 0x52,
	onSpellLevelup1 = 0x53,
	onSpellLevelup2 = 0x54,
	onSpellLevelup3 = 0x55,
	onSpellLevelup4 = 0x56,
	onSpellEvolve1 = 0x57,
	onSpellEvolve2 = 0x58,
	onSpellEvolve3 = 0x59,
	onSpellEvolve4 = 0x5A,
	onItemPurchased = 0x5B,
	onItemSold = 0x5C,
	onItemRemoved = 0x5D,
	onItemUndo = 0x5E,
	onItemCallout = 0x5F,
	onItemChange = 0x60,
	onUndoEnabledChange = 0x61,
	onShopItemSubstitutionChange = 0x62,
	onSurrenderVoteStart = 0x63,
	onSurrenderVote = 0x64,
	onSurrenderVoteAlready = 0x65,
	onSurrenderFailedVotes = 0x66,
	onSurrenderTooEarly = 0x67,
	onSurrenderAgreed = 0x68,
	onSurrenderSpam = 0x69,
	onSurrenderEarlyAllowed = 0x6A,
	onEqualizeVoteStart = 0x6B,
	onEqualizeVote = 0x6C,
	onEqualizeVoteAlready = 0x6D,
	onEqualizeFailedVotes = 0x6E,
	onEqualizeTooEarly = 0x6F,
	onEqualizeNotEnoughGold = 0x70,
	onEqualizeNotEnoughLevels = 0x71,
	onEqualizeAgreed = 0x72,
	onEqualizeSpam = 0x73,
	onPause = 0x74,
	onPauseResume = 0x75,
	onMinionsSpawn = 0x76,
	onStartGameMessage1 = 0x77,
	onStartGameMessage2 = 0x78,
	onStartGameMessage3 = 0x79,
	onStartGameMessage4 = 0x7A,
	onStartGameMessage5 = 0x7B,
	onAlert = 0x7C,
	onScoreboardOpen = 0x7D,
	onAudioEventFinished = 0x7E,
	onNexusCrystalStart = 0x7F,
	onCapturePointNeutralizedA = 0x80,
	onCapturePointNeutralizedB = 0x81,
	onCapturePointNeutralizedC = 0x82,
	onCapturePointNeutralizedD = 0x83,
	onCapturePointNeutralizedE = 0x84,
	onCapturePointCapturedA = 0x85,
	onCapturePointCapturedB = 0x86,
	onCapturePointCapturedC = 0x87,
	onCapturePointCapturedD = 0x88,
	onCapturePointCapturedE = 0x89,
	onCapturePointFiveCap = 0x8A,
	onVictoryPointThreshold1 = 0x8B,
	onVictoryPointThreshold2 = 0x8C,
	onVictoryPointThreshold3 = 0x8D,
	onVictoryPointThreshold4 = 0x8E,
	onMinionKillVictoryThreshold1 = 0x8F,
	onMinionKillVictoryThreshold2 = 0x90,
	onTurretKillVictoryThreshold1 = 0x91,
	onTurretKillVictoryThreshold2 = 0x92,
	onReplayFastForwardStart = 0x93,
	onReplayFastForwardEnd = 0x94,
	onReplayOnKeyframeFinished = 0x95,
	onReplayDestroyAllObjects = 0x96,
	onKillDragon = 0x97,
	onKillDragonSpectator = 0x98,
	onKillDragonSteal = 0x99,
	onKillWorm = 0x9A,
	onKillWormSpectator = 0x9B,
	onKillWormSteal = 0x9C,
	onKillSpiderBoss = 0x9D,
	onKillSpiderBossSpectator = 0x9E,
	onCaptureAltar = 0x9F,
	onCaptureAltarSpectator = 0xA0,
	onPlaceWard = 0xA1,
	onKillWard = 0xA2,
	onMinionAscended = 0xA3,
	onChampionAscended = 0xA4,
	onClearAscended = 0xA5,
	onGameStatEvent = 0xA6,
}

export const OnEventArguments = {
	[OnEvent.onDelete]: OnEventParam.base,
	[OnEvent.onSpawn]: OnEventParam.die,
	[OnEvent.onDie]: OnEventParam.die,
	[OnEvent.onKill]: OnEventParam.base,
	[OnEvent.onChampionDie]: OnEventParam.die,
	[OnEvent.onChampionKillPre]: OnEventParam.championKillPre,
	[OnEvent.onChampionKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionKillPost]: OnEventParam.championKillPre,
	[OnEvent.onChampionSingleKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionDoubleKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionTripleKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionQuadraKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionPentaKill]: OnEventParam.championKillPre,
	[OnEvent.onChampionUnrealKill]: OnEventParam.championKillPre,
	[OnEvent.onFirstBlood]: OnEventParam.base,
	[OnEvent.onDamageTaken]: OnEventParam.damage,
	[OnEvent.onDamageGiven]: OnEventParam.damage,
	[OnEvent.onSpellCast1]: OnEventParam.base,
	[OnEvent.onSpellCast2]: OnEventParam.base,
	[OnEvent.onSpellCast3]: OnEventParam.base,
	[OnEvent.onSpellCast4]: OnEventParam.base,
	[OnEvent.onSpellAvatarCast1]: OnEventParam.base,
	[OnEvent.onSpellAvatarCast2]: OnEventParam.base,
	[OnEvent.onGoldSpent]: OnEventParam.goldSpent,
	[OnEvent.onGoldEarned]: OnEventParam.goldEarned,
	[OnEvent.onItemConsumeablePurchased]: OnEventParam.itemConsumedPurchased,
	[OnEvent.onCriticalStrike]: OnEventParam.damageCriticalStrike,
	[OnEvent.onAce]: OnEventParam.base,
	[OnEvent.onReincarnate]: OnEventParam.base,
	[OnEvent.onChangeChampion]: OnEventParam.base,
	[OnEvent.onDampenerKill]: OnEventParam.base,
	[OnEvent.onDampenerDie]: OnEventParam.die,
	[OnEvent.onDampenerRespawnSoon]: OnEventParam.base,
	[OnEvent.onDampenerRespawn]: OnEventParam.base,
	[OnEvent.onDampenerDamage]: OnEventParam.base,
	[OnEvent.onTurretKill]: OnEventParam.base,
	[OnEvent.onTurretDie]: OnEventParam.die,
	[OnEvent.onTurretDamage]: OnEventParam.die,
	[OnEvent.onMinionKill]: OnEventParam.die,
	[OnEvent.onMinionDenied]: OnEventParam.base,
	[OnEvent.onNeutralMinionKill]: OnEventParam.minionKill,
	[OnEvent.onSuperMonsterKill]: OnEventParam.base,
	[OnEvent.onAcquireRedBuffFromNeutral]: OnEventParam.base,
	[OnEvent.onAcquireBlueBuffFromNeutral]: OnEventParam.base,
	[OnEvent.onHqKill]: OnEventParam.base,
	[OnEvent.onHqDie]: OnEventParam.base,
	[OnEvent.onHeal]: OnEventParam.heal,
	[OnEvent.onCastHeal]: OnEventParam.heal,
	[OnEvent.onBuff]: OnEventParam.buff,
	[OnEvent.onCrowdControlDealt]: OnEventParam.cc,
	[OnEvent.onKillingSpree]: OnEventParam.killingSpree,
	[OnEvent.onKillingSpreeSet1]: OnEventParam.base,
	[OnEvent.onKillingSpreeSet2]: OnEventParam.base,
	[OnEvent.onKillingSpreeSet3]: OnEventParam.base,
	[OnEvent.onKillingSpreeSet4]: OnEventParam.base,
	[OnEvent.onKillingSpreeSet5]: OnEventParam.base,
	[OnEvent.onKillingSpreeSet6]: OnEventParam.base,
	[OnEvent.onKilledUnitOnKillingSpree]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet1]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet2]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet3]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet4]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet5]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeSet6]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeDoubleKill]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeTripleKill]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeQuadraKill]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreePentaKill]: OnEventParam.championKillPre,
	[OnEvent.onKilledUnitOnKillingSpreeUnrealKill]: OnEventParam.championKillPre,
	[OnEvent.onDeathAssist]: OnEventParam.assist,
	[OnEvent.onQuit]: OnEventParam.base,
	[OnEvent.onLeave]: OnEventParam.base,
	[OnEvent.onReconnect]: OnEventParam.base,
	[OnEvent.onGameStart]: OnEventParam.base,
	[OnEvent.onAssistingSpreeSet1]: OnEventParam.base,
	[OnEvent.onAssistingSpreeSet2]: OnEventParam.base,
	[OnEvent.onChampionTripleAssist]: OnEventParam.base,
	[OnEvent.onChampionPentaAssist]: OnEventParam.base,
	[OnEvent.onPing]: OnEventParam.base,
	[OnEvent.onPingPlayer]: OnEventParam.base,
	[OnEvent.onPingBuilding]: OnEventParam.base,
	[OnEvent.onPingOther]: OnEventParam.base,
	[OnEvent.onEndGame]: OnEventParam.base,
	[OnEvent.onSpellLevelup1]: OnEventParam.base,
	[OnEvent.onSpellLevelup2]: OnEventParam.base,
	[OnEvent.onSpellLevelup3]: OnEventParam.base,
	[OnEvent.onSpellLevelup4]: OnEventParam.base,
	[OnEvent.onSpellEvolve1]: OnEventParam.base,
	[OnEvent.onSpellEvolve2]: OnEventParam.base,
	[OnEvent.onSpellEvolve3]: OnEventParam.base,
	[OnEvent.onSpellEvolve4]: OnEventParam.base,
	[OnEvent.onItemPurchased]: OnEventParam.itemConsumedPurchased,
	[OnEvent.onItemSold]: OnEventParam.itemSoldOrRemoved,
	[OnEvent.onItemRemoved]: OnEventParam.itemSoldOrRemoved,
	[OnEvent.onItemUndo]: OnEventParam.itemUndo,
	[OnEvent.onItemCallout]: OnEventParam.itemCallout,
	[OnEvent.onItemChange]: OnEventParam.itemChange,
	[OnEvent.onUndoEnabledChange]: OnEventParam.undoEnabledChange,
	[OnEvent.onShopItemSubstitutionChange]: OnEventParam.shopItemSubstitutionChange,
	[OnEvent.onSurrenderVoteStart]: OnEventParam.base,
	[OnEvent.onSurrenderVote]: OnEventParam.base,
	[OnEvent.onSurrenderVoteAlready]: OnEventParam.base,
	[OnEvent.onSurrenderFailedVotes]: OnEventParam.base,
	[OnEvent.onSurrenderTooEarly]: OnEventParam.base,
	[OnEvent.onSurrenderAgreed]: OnEventParam.base,
	[OnEvent.onSurrenderSpam]: OnEventParam.base,
	[OnEvent.onSurrenderEarlyAllowed]: OnEventParam.base,
	[OnEvent.onEqualizeVoteStart]: OnEventParam.base,
	[OnEvent.onEqualizeVote]: OnEventParam.base,
	[OnEvent.onEqualizeVoteAlready]: OnEventParam.base,
	[OnEvent.onEqualizeFailedVotes]: OnEventParam.base,
	[OnEvent.onEqualizeTooEarly]: OnEventParam.base,
	[OnEvent.onEqualizeNotEnoughGold]: OnEventParam.base,
	[OnEvent.onEqualizeNotEnoughLevels]: OnEventParam.base,
	[OnEvent.onEqualizeAgreed]: OnEventParam.base,
	[OnEvent.onEqualizeSpam]: OnEventParam.base,
	[OnEvent.onPause]: OnEventParam.base,
	[OnEvent.onPauseResume]: OnEventParam.base,
	[OnEvent.onMinionsSpawn]: OnEventParam.base,
	[OnEvent.onStartGameMessage1]: OnEventParam.globalMessageGeneric,
	[OnEvent.onStartGameMessage2]: OnEventParam.globalMessageGeneric,
	[OnEvent.onStartGameMessage3]: OnEventParam.globalMessageGeneric,
	[OnEvent.onStartGameMessage4]: OnEventParam.globalMessageGeneric,
	[OnEvent.onStartGameMessage5]: OnEventParam.globalMessageGeneric,
	[OnEvent.onAlert]: OnEventParam.alert,
	[OnEvent.onScoreboardOpen]: OnEventParam.base,
	[OnEvent.onAudioEventFinished]: OnEventParam.base,
	[OnEvent.onNexusCrystalStart]: OnEventParam.base,
	[OnEvent.onCapturePointNeutralizedA]: OnEventParam.base,
	[OnEvent.onCapturePointNeutralizedB]: OnEventParam.base,
	[OnEvent.onCapturePointNeutralizedC]: OnEventParam.base,
	[OnEvent.onCapturePointNeutralizedD]: OnEventParam.base,
	[OnEvent.onCapturePointNeutralizedE]: OnEventParam.base,
	[OnEvent.onCapturePointCapturedA]: OnEventParam.base,
	[OnEvent.onCapturePointCapturedB]: OnEventParam.base,
	[OnEvent.onCapturePointCapturedC]: OnEventParam.base,
	[OnEvent.onCapturePointCapturedD]: OnEventParam.base,
	[OnEvent.onCapturePointCapturedE]: OnEventParam.base,
	[OnEvent.onCapturePointFiveCap]: OnEventParam.base,
	[OnEvent.onVictoryPointThreshold1]: OnEventParam.base,
	[OnEvent.onVictoryPointThreshold2]: OnEventParam.base,
	[OnEvent.onVictoryPointThreshold3]: OnEventParam.base,
	[OnEvent.onVictoryPointThreshold4]: OnEventParam.base,
	[OnEvent.onMinionKillVictoryThreshold1]: OnEventParam.base,
	[OnEvent.onMinionKillVictoryThreshold2]: OnEventParam.base,
	[OnEvent.onTurretKillVictoryThreshold1]: OnEventParam.base,
	[OnEvent.onTurretKillVictoryThreshold2]: OnEventParam.base,
	[OnEvent.onReplayFastForwardStart]: OnEventParam.base,
	[OnEvent.onReplayFastForwardEnd]: OnEventParam.base,
	[OnEvent.onReplayOnKeyframeFinished]: OnEventParam.base,
	[OnEvent.onReplayDestroyAllObjects]: OnEventParam.base,
	[OnEvent.onKillDragon]: OnEventParam.minionKill,
	[OnEvent.onKillDragonSpectator]: OnEventParam.minionKill,
	[OnEvent.onKillDragonSteal]: OnEventParam.minionKill,
	[OnEvent.onKillWorm]: OnEventParam.minionKill,
	[OnEvent.onKillWormSpectator]: OnEventParam.minionKill,
	[OnEvent.onKillWormSteal]: OnEventParam.minionKill,
	[OnEvent.onKillSpiderBoss]: OnEventParam.minionKill,
	[OnEvent.onKillSpiderBossSpectator]: OnEventParam.minionKill,
	[OnEvent.onCaptureAltar]: OnEventParam.capturePoint,
	[OnEvent.onCaptureAltarSpectator]: OnEventParam.capturePoint,
	[OnEvent.onPlaceWard]: OnEventParam.base,
	[OnEvent.onKillWard]: OnEventParam.base,
	[OnEvent.onMinionAscended]: OnEventParam.base,
	[OnEvent.onChampionAscended]: OnEventParam.base,
	[OnEvent.onClearAscended]: OnEventParam.base,
	[OnEvent.onGameStatEvent]: OnEventParam.base,
} as const;
