var Packets = {
	Header: {
		cmd: 'uint8',
		netId: 'uint32',
	},
	HANDSHAKE: {
		id: 0,
		KEY_CHECK:							{id: 0x00, packet: require('./Packets/HANDSHAKE/0x00-KEY_CHECK.js')},
		SPM_HierarchicalProfilerUpdate:		{id: 0x01},
	},
	LOADING_SCREEN: {
		id: 7,
		CLIENT_READY:						{id: 0x64, packet: require('./Packets/LOADING_SCREEN/0x64-CLIENT_READY.js')},
		LOAD_HERO:							{id: 0x65, packet: require('./Packets/LOADING_SCREEN/0x65-LOAD_HERO.js')},
		LOAD_NAME:							{id: 0x66, packet: require('./Packets/LOADING_SCREEN/0x66-LOAD_NAME.js')},
		LOAD_SCREEN_INFO:					{id: 0x67, packet: require('./Packets/LOADING_SCREEN/0x67-LOAD_SCREEN_INFO.js')},
	
	},
	GAMEPLAY: {
		id: 2,
		HEART_BEAT:							{id: 0x08, packet: require('./Packets/GAMEPLAY/0x08-HEART_BEAT.js')},
		SyncSimTimeFinal:					{id: 0x76, packet: require('./Packets/GAMEPLAY/0x76-SyncSimTimeFinal.js')},
	},
	LOW_PRIORITY: {
		id: 4,
		MOVE_ANS:							{id: 0x61, packet: require('./Packets/LOW_PRIORITY/0x61-MOVE_ANS.js')},
		PING_LOAD_INFO:						{id: 0x95, packet: require('./Packets/LOW_PRIORITY/0x95-PING_LOAD_INFO.js')},
		CHAR_STATS:							{id: 0xC4, packet: require('./Packets/LOW_PRIORITY/0xC4-CHAR_STATS.js')},
	},
	COMMUNICATION: {
		id: 5,
		CHAT_BOX_MESSAGE:					{id: 0x68, packet: require('./Packets/COMMUNICATION/0x68-CHAT_BOX_MESSAGE.js')},
	},
	C2S: {
		id: 1,
		SELL_ITEM:							{id: 0x09},
		UNPAUSE_GAME:						{id: 0x0A},
		QUERY_STATUS_REQ:					{id: 0x14, packet: require('./Packets/BasePacket.js')},
		PING_LOAD_INFO:						{id: 0x16, packet: require('./Packets/C2S/0x16-PING_LOAD_INFO.js')},
		SWAP_ITEMS:							{id: 0x20},
		VIEW_REQ:							{id: 0x2E, packet: require('./Packets/C2S/0x2E-VIEW_REQ.js')},
		SKILL_UPGRADE:						{id: 0x39, packet: require('./Packets/C2S/0x39-SKILL_UPGRADE.js')},
		USE_OBJECT:							{id: 0x3A},
		AUTO_ATTACK_OPTION:					{id: 0x47, packet: require('./Packets/C2S/0x47-AUTO_ATTACK_OPTION.js')},
		EMOTION:							{id: 0x48, packet: require('./Packets/C2S/0x48-EMOTION.js')},
		START_GAME:							{id: 0x52, packet: require('./Packets/C2S/0x52-START_GAME.js')},
		SCOREBOARD:							{id: 0x56, packet: require('./Packets/C2S/0x56-SCOREBOARD.js')},
		ATTENTION_PING:						{id: 0x57, packet: require('./Packets/C2S/0x57-ATTENTION_PING.js')},
		BLUE_TIP_CLICKED:					{id: 0x6D},
		MOVE_REQ:							{id: 0x72, packet: require('./Packets/C2S/0x72-MOVE_REQ.js')},
		MOVE_CONFIRM:						{id: 0x77, packet: require('./Packets/C2S/0x77-MOVE_CONFIRM.js')},
		LOCK_CAMERA:						{id: 0x81, packet: require('./Packets/C2S/0x81-LOCK_CAMERA.js')},
		BUY_ITEM_REQ:						{id: 0x82},
		EXIT:								{id: 0x8F, packet: require('./Packets/BasePacket.js')},
		WORLD_SEND_GAME_NUMBER:				{id: 0x92},
		CAST_SPELL:							{id: 0x9A, packet: require('./Packets/C2S/0x9A-CAST_SPELL.js')},
		PAUSE_GAME:							{id: 0xA1},
		SURRENDER:							{id: 0xA4},
		STATS_CONFIRM:						{id: 0xA8, packet: require('./Packets/C2S/0xA8-STATS_CONFIRM.js')},
		CLICK:								{id: 0xAF},
		SYNCH_VERSION:						{id: 0xBD, packet: require('./Packets/C2S/0xBD-SYNCH_VERSION.js')},
		CHAR_LOADED:						{id: 0xBE, packet: require('./Packets/C2S/0xBE-CHAR_LOADED.js')},
		QUEST_CLICKED:						{id: 0xCD},
		SPELL_CHARGE_UPDATE:				{id: 0xE6},
	},
	S2C: {
		id: 3,
    	DisplayLocalizedTutorialChatText:	{id: 0x02},
    	Barrack_SpawnUnit:					{id: 0x03, packet: require('./Packets/S2C/0x03-Barrack_SpawnUnit.js')},
    	SwitchNexusesToOnIdleParticles:		{id: 0x04},
    	TutorialAudioEventFinished:			{id: 0x05},
		SetCircularMovementRestriction:		{id: 0x06, packet: require('./Packets/S2C/0x06-SetCircularMovementRestriction.js')},
    	UpdateGoldRedirectTarget:			{id: 0x07, packet: require('./Packets/S2C/0x07-UpdateGoldRedirectTarget.js')},
		REMOVE_ITEM:						{id: 0x0B, packet: require('./Packets/S2C/0x0B-REMOVE_ITEM.js')},
		NEXT_AUTO_ATTACK:					{id: 0x0C, packet: require('./Packets/S2C/0x0C-NEXT_AUTO_ATTACK.js')},
		EDIT_MESSAGE_BOX_TOP:				{id: 0x0D},
		UNLOCK_CAMERA:						{id: 0x0E, packet: require('./Packets/S2C/0x0E-UNLOCK_CAMERA.js')},
		ADD_XP:								{id: 0x10, packet: require('./Packets/S2C/0x10-ADD_XP.js')},
		END_SPAWN:							{id: 0x11, packet: require('./Packets/S2C/0x11-END_SPAWN.js')},
		GAME_SPEED:							{id: 0x12},
		SKILL_UP:							{id: 0x15, packet: require('./Packets/S2C/0x15-SKILL_UP.js')},
		CHANGE_SPELL:						{id: 0x17, packet: require('./Packets/S2C/0x17-CHANGE_SPELL.js')},
		FLOATING_TEXT:						{id: 0x18, packet: require('./Packets/S2C/0x18-FLOATING_TEXT.js')},
		FLOATING_TEXT_WITH_VALUE:			{id: 0x19},
		BEGIN_AUTO_ATTACK:					{id: 0x1A, packet: require('./Packets/S2C/0x1A-BEGIN_AUTO_ATTACK.js')},
		CHAMPION_DIE2:						{id: 0x1B},
		EDIT_BUFF:							{id: 0x1C, packet: require('./Packets/S2C/0x1C-EDIT_BUFF.js')},
		NPC_SetAutocast:					{id: 0x1F, packet: require('./Packets/S2C/0x1F-NPC_SetAutocast.js')},
		ADD_GOLD:							{id: 0x22, packet: require('./Packets/S2C/0x22-ADD_GOLD.js')},
		FOG_UPDATE2:						{id: 0x23, packet: require('./Packets/S2C/0x23-FOG_UPDATE2.js')},
		MOVE_CAMERA:						{id: 0x25, packet: require('./Packets/S2C/0x25-MOVE_CAMERA.js')},
		LineMissileHitList:					{id: 0x26, packet: require('./Packets/S2C/0x26-LineMissileHitList.js')},
		SOUND_SETTINGS:						{id: 0x27},
		StopAnimation:						{id: 0x29, packet: require('./Packets/S2C/0x29-StopAnimation.js')},
		AVATAR_INFO:						{id: 0x2A, packet: require('./Packets/S2C/0x2A-AVATAR_INFO.js')},
		INHIBITOR_STATE:					{id: 0x2B, packet: require('./Packets/S2C/0x2B-INHIBITOR_STATE.js')},
		VIEW_ANS:							{id: 0x2C, packet: require('./Packets/S2C/0x2C-VIEW_ANS.js')},
		CHAMPION_RESPAWN:					{id: 0x2F, packet: require('./Packets/S2C/0x2F-CHAMPION_RESPAWN.js')},
		NPC_BuffReplace:					{id: 0x30, packet: require('./Packets/S2C/0x30-NPC_BuffReplace.js')},
		SetFadeOut_Pop:						{id: 0x32, packet: require('./Packets/S2C/0x32-SetFadeOut_Pop.js')},
		ADD_UNIT_FOW:						{id: 0x33, packet: require('./Packets/S2C/0x33-ADD_UNIT_FOW.js')},
		STOP_AUTO_ATTACK:					{id: 0x34, packet: require('./Packets/S2C/0x34-STOP_AUTO_ATTACK.js')},
		DELETE_OBJECT:						{id: 0x35, packet: require('./Packets/S2C/0x35-DELETE_OBJECT.js')},
		MESSAGE_BOX_TOP:					{id: 0x36},
		DESTROY_OBJECT:						{id: 0x38, packet: require('./Packets/S2C/0x38-DESTROY_OBJECT.js')},
		SPAWN_PROJECTILE:					{id: 0x3B, packet: require('./Packets/S2C/0x3B-SPAWN_PROJECTILE.js')},
		SWAP_ITEMS:							{id: 0x3E, packet: require('./Packets/S2C/0x3E-SWAP_ITEMS.js')},
		LEVEL_UP:							{id: 0x3F, packet: require('./Packets/S2C/0x3F-LEVEL_UP.js')},
		ATTENTION_PING:						{id: 0x40, packet: require('./Packets/S2C/0x40-ATTENTION_PING.js')},
		EMOTION:							{id: 0x42, packet: require('./Packets/S2C/0x42-EMOTION.js')},
		PLAY_SOUND:							{id: 0x43},
		PlayVOCommand:						{id: 0x44, packet: require('./Packets/S2C/0x44-PlayVOCommand.js')},
		ANNOUNCE:							{id: 0x45, packet: require('./Packets/S2C/0x45-ANNOUNCE.js')},
		PLAYER_STATS:						{id: 0x46, packet: require('./Packets/S2C/0x46-PLAYER_STATS.js')},
		HERO_SPAWN:							{id: 0x4C, packet: require('./Packets/S2C/0x4C-HERO_SPAWN.js')},
		FACE_DIRECTION:						{id: 0x50, packet: require('./Packets/S2C/0x50-FACE_DIRECTION.js')},
		LEAVE_VISION:						{id: 0x51, packet: require('./Packets/S2C/0x51-LEAVE_VISION.js')},
		SYNCH_VERSION:						{id: 0x54, packet: require('./Packets/S2C/0x54-SYNCH_VERSION.js')},
		BLUE_TIP:							{id: 0x55, packet: require('./Packets/S2C/0x55-BLUE_TIP.js')},
		HIGHLIGHT_UNIT:						{id: 0x59},
		DESTROY_PROJECTILE:					{id: 0x5A, packet: require('./Packets/S2C/0x5A-DESTROY_PROJECTILE.js')},
		START_GAME:							{id: 0x5C, packet: require('./Packets/S2C/0x5C-START_GAME.js')},
		CHAMPION_DIE:						{id: 0x5E, packet: require('./Packets/S2C/0x5E-CHAMPION_DIE.js')},
		FadeOutMainSFX:						{id: 0x5F, packet: require('./Packets/S2C/0x5F-FadeOutMainSFX.js')},
		START_SPAWN:						{id: 0x62, packet: require('./Packets/S2C/0x62-START_SPAWN.js')},
		DASH:								{id: 0x64, packet: require('./Packets/S2C/0x64-DASH.js')},
		DAMAGE_DONE:						{id: 0x65, packet: require('./Packets/S2C/0x65-DAMAGE_DONE.js')},
		MODIFY_SHIELD:						{id: 0x66, packet: require('./Packets/S2C/0x66-MODIFY_SHIELD.js')},
		SET_TARGET:							{id: 0x6A, packet: require('./Packets/S2C/0x6A-SET_TARGET.js')},
		SET_ANIMATION:						{id: 0x6B, packet: require('./Packets/S2C/0x6B-SET_ANIMATION.js')},
		SHOW_PROJECTILE:					{id: 0x6E, packet: require('./Packets/S2C/0x6E-SHOW_PROJECTILE.js')},
		BUY_ITEM_ANS:						{id: 0x6F, packet: require('./Packets/S2C/0x6F-BUY_ITEM_ANS.js')},
		FREEZE_UNIT_ANIMATION:				{id: 0x71},
		SET_CAMERA_POSITION:				{id: 0x73, packet: require('./Packets/S2C/0x73-SET_CAMERA_POSITION.js')},
		REMOVE_BUFF:						{id: 0x7B, packet: require('./Packets/S2C/0x7B-REMOVE_BUFF.js')},
		ToolTipVars:						{id: 0x7F, packet: require('./Packets/S2C/0x7F-ToolTipVars.js')},
		TOGGLE_INPUT_LOCKING_FLAG:			{id: 0x84, packet: require('./Packets/S2C/0x84-TOGGLE_INPUT_LOCKING_FLAG.js')},
		SET_COOLDOWN:						{id: 0x85, packet: require('./Packets/S2C/0x85-SET_COOLDOWN.js')},
		SPAWN_PARTICLE:						{id: 0x87, packet: require('./Packets/S2C/0x87-SPAWN_PARTICLE.js')},
		QUERY_STATUS_ANS:					{id: 0x88, packet: require('./Packets/S2C/0x88-QUERY_STATUS_ANS.js')},
		Building_Die:						{id: 0x89, packet: require('./Packets/S2C/0x89-Building_Die.js')},
		QUEST:								{id: 0x8C},
		WORLD_SEND_GAME_NUMBER:				{id: 0x92, packet: require('./Packets/S2C/0x92-WORLD_SEND_GAME_NUMBER.js')},
		NPC_BuffRemoveGroup:				{id: 0x94, packet: require('./Packets/S2C/0x94-NPC_BuffRemoveGroup.js')},
		CHANGE_CHARACTER_VOICE:				{id: 0x96, packet: require('./Packets/S2C/0x96-CHANGE_CHARACTER_VOICE.js')},
		UPDATE_MODEL:						{id: 0x97},
		DISCONNECTED_ANNOUNCEMENT:			{id: 0x98, packet: require('./Packets/S2C/0x98-DISCONNECTED_ANNOUNCEMENT.js')},
		TURRET_SPAWN:						{id: 0x9D, packet: require('./Packets/S2C/0x9D-TURRET_SPAWN.js')},
		NPC_HIDE:							{id: 0x9E, packet: require('./Packets/S2C/0x9E-NPC_HIDE.js')},
		SET_ITEM_STACKS:					{id: 0x9F, packet: require('./Packets/S2C/0x9F-SET_ITEM_STACKS.js')},
		MESSAGE_BOX_RIGHT:					{id: 0xA0},
		REMOVE_MESSAGE_BOX_TOP:				{id: 0xA2},
		ANNOUNCE2:							{id: 0xA3, packet: require('./Packets/S2C/0xA3-ANNOUNCE2.js')},
		SURRENDER_RESULT:					{id: 0xA5, packet: require('./Packets/S2C/0xA5-SURRENDER_RESULT.js')},
		REMOVE_MESSAGE_BOX_RIGHT:			{id: 0xA7},
		SetGreyscaleEnabledWhenDead:		{id: 0xA9, packet: require('./Packets/S2C/0xA9-SetGreyscaleEnabledWhenDead.js')},
		ENABLE_FOW:							{id: 0xAB},
		SET_HEALTH:							{id: 0xAE, packet: require('./Packets/S2C/0xAE-SET_HEALTH.js')},
		SPELL_ANIMATION:					{id: 0xB0, packet: require('./Packets/S2C/0xB0-SPELL_ANIMATION.js')},
		EDIT_MESSAGE_BOX_RIGHT:				{id: 0xB1},
		SET_MODEL_TRANSPARENCY:				{id: 0xB2, packet: require('./Packets/S2C/0xB2-SET_MODEL_TRANSPARENCY.js')},
		BASIC_TUTORIAL_MESSAGE_WINDOW:		{id: 0xB3},
		REMOVE_HIGHLIGHT_UNIT:				{id: 0xB4},
		CAST_SPELL_ANS:						{id: 0xB5, packet: require('./Packets/S2C/0xB5-CAST_SPELL_ANS.js')},
		ADD_BUFF:							{id: 0xB7, packet: require('./Packets/S2C/0xB7-ADD_BUFF.js')},
		AFK_WARNING_WINDOW:					{id: 0xB8},
		OBJECT_SPAWN:						{id: 0xBA, packet: require('./Packets/S2C/0xBA-OBJECT_SPAWN.js')},
		HIDE_UI:							{id: 0xBC, packet: require('./Packets/S2C/0xBC-HIDE_UI.js')},
		NPC_BuffUpdateCountGroup:			{id: 0xBF, packet: require('./Packets/S2C/0xBF-NPC_BuffUpdateCountGroup.js')},
		SET_TARGET2:						{id: 0xC0, packet: require('./Packets/S2C/0xC0-SET_TARGET2.js')},
		GAME_TIMER:							{id: 0xC1, packet: require('./Packets/S2C/0xC1-GAME_TIMER.js')},
		GAME_TIMER_UPDATE:					{id: 0xC2, packet: require('./Packets/S2C/0xC2-GAME_TIMER_UPDATE.js')},
		Neutral_Camp_Empty:					{id: 0xC3, packet: require('./Packets/S2C/0xC3-Neutral_Camp_Empty.js')},
		GAME_END:							{id: 0xC6, packet: require('./Packets/S2C/0xC6-GAME_END.js')},
		SURRENDER:							{id: 0xC9, packet: require('./Packets/S2C/0xC9-SURRENDER.js')},
		FadeMinions:						{id: 0xCB, packet: require('./Packets/S2C/0xCB-FadeMinions.js')},
		SHOW_HP_AND_NAME:					{id: 0xCE, packet: require('./Packets/S2C/0xCE-SHOW_HP_AND_NAME.js')},
		LEVEL_PROP_SPAWN:					{id: 0xD0, packet: require('./Packets/S2C/0xD0-LEVEL_PROP_SPAWN.js')},
		LEVEL_PROP_ANIMATION:				{id: 0xD1, packet: require('./Packets/S2C/0xD1-LEVEL_PROP_ANIMATION.js')},
		SET_CAPTURE_POINT:					{id: 0xD3},
		CHANGE_CRYSTAL_SCAR_NEXUS_HP:		{id: 0xD4},
		SET_TEAM:							{id: 0xD7},
		ATTACH_MINIMAP_ICON:				{id: 0xD8, packet: require('./Packets/S2C/0xD8-ATTACH_MINIMAP_ICON.js')},
		DOMINION_POINTS:					{id: 0xD9},
		SET_SCREEN_TINT:					{id: 0xDB},
		ColorRemapFX:						{id: 0xDB, packet: require('./Packets/S2C/0xDB-ColorRemapFX.js')},
		InteractiveMusicCommand:			{id: 0xDC, packet: require('./Packets/S2C/0xDC-InteractiveMusicCommand.js')},
		CLOSE_GAME:							{id: 0xE5},
		ActivateMinionCamp:					{id: 0xE9, packet: require('./Packets/S2C/0xE9-ActivateMinionCamp.js')},
		SetShopEnabled:						{id: 0xF0, packet: require('./Packets/S2C/0xF0-SetShopEnabled.js')},
		DEBUG_MESSAGE:						{id: 0xF7, packet: require('./Packets/S2C/0xF7-DEBUG_MESSAGE.js')},
		ChangeEmitterGroup:					{id: 0xF8, packet: require('./Packets/S2C/0xF8-ChangeEmitterGroup.js')},
		MESSAGES_AVAILABLE:					{id: 0xF9},
		SET_ITEM_STACKS2:					{id: 0xFD, packet: require('./Packets/S2C/0xFD-SET_ITEM_STACKS2.js')},
		EXTENDED:							{id: 0xFE},
		BATCH:								{id: 0xFF},
		SURRENDER_STATE:					{id: 0x10E},
		ON_ATTACK:							{id: 0x10F},
		CHAMPION_DEATH_TIMER:				{id: 0x117},
		SET_SPELL_ACTIVE_STATE:				{id: 0x118},
		RESOURCE_TYPE:						{id: 0x119},
		REPLACE_STORE_ITEM:					{id: 0x11C},
		CREATE_MONSTER_CAMP:				{id: 0x122},
		SPELL_EMPOWER:						{id: 0x125},
		NPC_DIE:							{id: 0x126},
		FLOATING_TEXT2:						{id: 0x128},
		FORCE_TARGET_SPELL:					{id: 0x129},
		MOVE_CHAMPION_CAMERA_CENTER:		{id: 0x12B},
	},
};

for(var i in Packets){
	if(typeof Packets[i].id != 'undefined'){
		Packets[i].name = i;
		Packets[Packets[i].id] = Packets[i];
		
		for(var j in Packets[i]){
			if(typeof Packets[i][j].id != 'undefined'){
				Packets[i][j].name = j;
				Packets[i][j].channel = Packets[i].id;
				Packets[i][Packets[i][j].id] = Packets[i][j];
			}
		}
	}
}
//console.log(Packets);

module.exports = Packets;
