
import fs from 'fs';
import '../../src/core/init_utilities.js';
import channels from '../../src/packets/channels.js';

let packetEnum = `{
	PKT_Dummy = 0x0,
	PKT_SPM_HierarchicalProfilerUpdate = 0x1,
	PKT_S2C_DisplayLocalizedTutorialChatText = 0x2,
	PKT_Barrack_SpawnUnit = 0x3,
	PKT_S2C_SwitchNexusesToOnIdleParticles = 0x4,
	PKT_C2S_TutorialAudioEventFinished = 0x5,
	PKT_S2C_SetCircularMovementRestriction = 0x6,
	PKT_UpdateGoldRedirectTarget = 0x7,
	PKT_SynchSimTimeC2S = 0x8,
	PKT_RemoveItemReq = 0x9,
	PKT_ResumePacket = 0xA,
	PKT_RemoveItemAns = 0xB,
	PKT_Basic_Attack = 0xC,
	PKT_S2C_ReplaceObjectiveText = 0xD,
	PKT_S2C_CloseShop = 0xE,
	PKT_S2C_Reconnect = 0xF,
	PKT_UnitAddEXP = 0x10,
	PKT_S2C_EndSpawn = 0x11,
	PKT_SetFrequency = 0x12,
	PKT_S2C_BotAI = 0x13,
	PKT_C2S_QueryStatusReq = 0x14,
	PKT_NPC_UpgradeSpellAns = 0x15,
	PKT_C2S_Ping_Load_Info = 0x16,
	PKT_ChangeSlotSpellData = 0x17,
	PKT_NPC_MessageToClient = 0x18,
	PKT_DisplayFloatingText = 0x19,
	PKT_Basic_Attack_Pos = 0x1A,
	PKT_NPC_ForceDead = 0x1B,
	PKT_NPC_BuffUpdateCount = 0x1C,
	PKT_C2S_WriteNavFlags_Acc = 0x1D,
	PKT_NPC_BuffReplaceGroup = 0x1E,
	PKT_NPC_SetAutocast = 0x1F,
	PKT_SwapItemReq = 0x20,
	PKT_NPC_Die_EventHistory = 0x21,
	PKT_UnitAddGold = 0x22,
	PKT_AddRegion = 0x23,
	PKT_S2C_MoveRegion = 0x24,
	PKT_S2C_MoveCameraToPoint = 0x25,
	PKT_S2C_LineMissileHitList = 0x26,
	PKT_S2C_MuteVolumeCategory = 0x27,
	PKT_ServerTick = 0x28,
	PKT_S2C_StopAnimation = 0x29,
	PKT_AvatarInfo_Server = 0x2A,
	PKT_DampenerSwitchStates = 0x2B,
	PKT_World_SendCamera_Server_Acknologment = 0x2C,
	PKT_S2C_ModifyDebugCircleRadius = 0x2D,
	PKT_World_SendCamera_Server = 0x2E,
	PKT_HeroReincarnateAlive = 0x2F,
	PKT_NPC_BuffReplace = 0x30,
	PKT_Pause = 0x31,
	PKT_SetFadeOut_Pop = 0x32,
	PKT_RemoveRegion = 0x33,
	PKT_NPC_InstantStop_Attack = 0x34,
	PKT_OnLeaveLocalVisiblityClient = 0x35,
	PKT_S2C_ShowObjectiveText = 0x36,
	PKT_CHAR_SpawnPet = 0x37,
	PKT_FX_Kill = 0x38,
	PKT_NPC_UpgradeSpellReq = 0x39,
	PKT_UseObjectC2S = 0x3A,
	PKT_MissileReplication = 0x3B,
	PKT_MovementDriverReplication = 0x3C,
	PKT_S2C_HighlightHUDElement = 0x3D,
	PKT_SwapItemAns = 0x3E,
	PKT_NPC_LevelUp = 0x3F,
	PKT_S2C_MapPing = 0x40,
	PKT_S2C_WriteNavFlags = 0x41,
	PKT_S2C_PlayEmote = 0x42,
	PKT_S2C_PlaySound = 0x43,
	PKT_S2C_PlayVOCommand = 0x44,
	PKT_S2C_OnEventWorld = 0x45,
	PKT_S2C_HeroStats = 0x46,
	PKT_C2S_UpdateGameOptions = 0x47,
	PKT_C2S_PlayEmote = 0x48,
	PKT_C2S_PlayVOCommand = 0x49,
	PKT_HeroReincarnate = 0x4A,
	PKT_C2S_OnScoreBoardOpened = 0x4B,
	PKT_S2C_CreateHero = 0x4C,
	PKT_SPM_AddMemoryListener = 0x4D,
	PKT_SPM_HierarchicalMemoryUpdate = 0x4E,
	PKT_S2C_ToggleUIHighlight = 0x4F,
	PKT_S2C_FaceDirection = 0x50,
	PKT_OnLeaveVisiblityClient = 0x51,
	PKT_C2S_ClientReady = 0x52,
	PKT_SetItem = 0x53,
	PKT_SynchVersionS2C = 0x54,
	PKT_S2C_HandleTipUpdate = 0x55,
	PKT_C2S_StatsUpdateReq = 0x56,
	PKT_C2S_MapPing = 0x57,
	PKT_S2C_RemoveDebugObject = 0x58,
	PKT_S2C_CreateUnitHighlight = 0x59,
	PKT_S2C_DestroyClientMissile = 0x5A,
	PKT_S2C_SetSpellLevel = 0x5B,
	PKT_S2C_StartGame = 0x5C,
	PKT_C2S_OnShopOpened = 0x5D,
	PKT_NPC_Hero_Die = 0x5E,
	PKT_S2C_FadeOutMainSFX = 0x5F,
	PKT_S2C_PlayThemeMusic = 0x60,
	PKT_WaypointGroup = 0x61,
	PKT_S2C_StartSpawn = 0x62,
	PKT_S2C_CreateNeutral = 0x63,
	PKT_WaypointGroupWithSpeed = 0x64,
	PKT_UnitApplyDamage = 0x65,
	PKT_ModifyShield = 0x66,
	PKT_S2C_PopCharacterData = 0x67,
	PKT_NPC_BuffAddGroup = 0x68,
	PKT_S2C_AI_TargetSelection = 0x69,
	PKT_AI_TargetS2C = 0x6A,
	PKT_S2C_SetAnimStates = 0x6B,
	PKT_S2C_ChainMissileSync = 0x6C,
	PKT_C2S_OnTipEvent = 0x6D,
	PKT_S2C_ForceCreateMissile = 0x6E,
	PKT_BuyItemAns = 0x6F,
	PKT_S2C_SetSpellData = 0x70,
	PKT_S2C_PauseAnimation = 0x71,
	PKT_NPC_IssueOrderReq = 0x72,
	PKT_S2C_CameraBehavior = 0x73,
	PKT_S2C_AnimatedBuildingSetCurrentSkin = 0x74,
	PKT_Connected = 0x75,
	PKT_SyncSimTimeFinalS2C = 0x76,
	PKT_Waypoint_Acc = 0x77,
	PKT_S2C_LockCamera = 0x78,
	PKT_S2C_PlayVOAudioEvent = 0x79,
	PKT_AI_Command = 0x7A,
	PKT_NPC_BuffRemove2 = 0x7B,
	PKT_SpawnMinionS2C = 0x7C,
	PKT_ClientCheatDetectionSignal = 0x7D,
	PKT_S2C_ToggleFoW = 0x7E,
	PKT_S2C_ToolTipVars = 0x7F,
	PKT_Unused128 = 0x80,
	PKT_World_LockCamera_Server = 0x81,
	PKT_BuyItemReq = 0x82,
	PKT_WaypointListHeroWithSpeed = 0x83,
	PKT_S2C_SetInputLockFlag = 0x84,
	PKT_CHAR_SetCooldown = 0x85,
	PKT_CHAR_CancelTargetingReticle = 0x86,
	PKT_FX_Create_Group = 0x87,
	PKT_S2C_QueryStatusAns = 0x88,
	PKT_Building_Die = 0x89,
	PKT_S2C_PreloadCharacterData = 0x8A,
	PKT_SPM_RemoveListener = 0x8B,
	PKT_S2C_HandleQuestUpdate = 0x8C,
	PKT_C2S_ClientFinished = 0x8D,
	PKT_SPM_RemoveMemoryListener = 0x8E,
	PKT_C2S_Exit = 0x8F,
	PKT_S2C_ModifyDebugObjectColor = 0x90,
	PKT_SPM_AddListener = 0x91,
	PKT_World_SendGameNumber = 0x92,
	PKT_SetPARState = 0x93,
	PKT_NPC_BuffRemoveGroup = 0x94,
	PKT_S2C_Ping_Load_Info = 0x95,
	PKT_S2C_ChangeCharacterVoice = 0x96,
	PKT_S2C_ChangeCharacterData = 0x97,
	PKT_S2C_Exit = 0x98,
	PKT_SPM_RemoveBBProfileListener = 0x99,
	PKT_NPC_CastSpellReq = 0x9A,
	PKT_S2C_ToggleInputLockFlag = 0x9B,
	PKT_C2S_SoftReconnect = 0x9C,
	PKT_S2C_CreateTurret = 0x9D,
	PKT_NPC_Die = 0x9E,
	PKT_UseItemAns = 0x9F,
	PKT_S2C_ShowAuxiliaryText = 0xA0,
	PKT_PausePacket = 0xA1,
	PKT_S2C_HideObjectiveText = 0xA2,
	PKT_OnEvent = 0xA3,
	PKT_C2S_TeamSurrenderVote = 0xA4,
	PKT_S2C_TeamSurrenderStatus = 0xA5,
	PKT_SPM_AddBBProfileListener = 0xA6,
	PKT_S2C_HideAuxiliaryText = 0xA7,
	PKT_OnReplication_Acc = 0xA8,
	PKT_S2C_SetGreyscaleEnabledWhenDead = 0xA9,
	PKT_S2C_AI_State = 0xAA,
	PKT_S2C_SetFoWStatus = 0xAB,
	PKT_ReloadScripts = 0xAC,
	PKT_Cheat = 0xAD,
	PKT_OnEnterLocalVisiblityClient = 0xAE,
	PKT_SendSelectedObjID = 0xAF,
	PKT_S2C_PlayAnimation = 0xB0,
	PKT_S2C_RefreshAuxiliaryText = 0xB1,
	PKT_SetFadeOut_Push = 0xB2,
	PKT_S2C_OpenTutorialPopup = 0xB3,
	PKT_S2C_RemoveUnitHighlight = 0xB4,
	PKT_NPC_CastSpellAns = 0xB5,
	PKT_SPM_HierarchicalBBProfileUpdate = 0xB6,
	PKT_NPC_BuffAdd2 = 0xB7,
	PKT_S2C_OpenAFKWarningMessage = 0xB8,
	PKT_WaypointList = 0xB9,
	PKT_OnEnterVisiblityClient = 0xBA,
	PKT_S2C_AddDebugObject = 0xBB,
	PKT_S2C_DisableHUDForEndOfGame = 0xBC,
	PKT_SynchVersionC2S = 0xBD,
	PKT_C2S_CharSelected = 0xBE,
	PKT_NPC_BuffUpdateCountGroup = 0xBF,
	PKT_AI_TargetHeroS2C = 0xC0,
	PKT_SynchSimTimeS2C = 0xC1,
	PKT_SyncMissionStartTimeS2C = 0xC2,
	PKT_S2C_Neutral_Camp_Empty = 0xC3,
	PKT_OnReplication = 0xC4,
	PKT_S2C_EndOfGameEvent = 0xC5,
	PKT_S2C_EndGame = 0xC6,
	PKT_SPM_SamplingProfilerUpdate = 0xC7,
	PKT_S2C_PopAllCharacterData = 0xC8,
	PKT_S2C_TeamSurrenderVote = 0xC9,
	PKT_S2C_HandleUIHighlight = 0xCA,
	PKT_S2C_FadeMinions = 0xCB,
	PKT_C2S_OnTutorialPopupClosed = 0xCC,
	PKT_C2S_OnQuestEvent = 0xCD,
	PKT_S2C_ShowHealthBar = 0xCE,
	PKT_SpawnBotS2C = 0xCF,
	PKT_SpawnLevelPropS2C = 0xD0,
	PKT_UpdateLevelPropS2C = 0xD1,
	PKT_AttachFlexParticleS2C = 0xD2,
	PKT_S2C_HandleCapturePointUpdate = 0xD3,
	PKT_S2C_HandleGameScore = 0xD4,
	PKT_S2C_HandleRespawnPointUpdate = 0xD5,
	PKT_C2S_OnRespawnPointEvent = 0xD6,
	PKT_S2C_UnitChangeTeam = 0xD7,
	PKT_S2C_UnitSetMinimapIcon = 0xD8,
	PKT_S2C_IncrementPlayerScore = 0xD9,
	PKT_S2C_IncrementPlayerStat = 0xDA,
	PKT_S2C_ColorRemapFX = 0xDB,
	PKT_S2C_InteractiveMusicCommand = 0xDC,
	PKT_S2C_AntiBot = 0xDD,
	PKT_S2C_AntiBotAction = 0xDE,
	PKT_C2S_AntiBot = 0xDF,
	PKT_S2C_OnEnterTeamVisiblity = 0xE0,
	PKT_S2C_OnLeaveTeamVisiblity = 0xE1,
	PKT_S2C_FX_OnEnterTeamVisiblity = 0xE2,
	PKT_S2C_FX_OnLeaveTeamVisiblity = 0xE3,
	PKT_ReplayOnly_GoldEarned = 0xE4,
	PKT_S2C_CloseClient = 0xE5,
	PKT_C2S_SpellChargeUpdateReq = 0xE6,
	PKT_S2C_ModifyDebugText = 0xE7,
	PKT_S2C_SetDebugHidden = 0xE8,
	PKT_S2C_ActivateMinionCamp = 0xE9,
	PKT_C2S_SpectatorDataReq = 0xEA,
	PKT_S2C_SpectatorMetaData = 0xEB,
	PKT_S2C_SpectatorDataChunkInfo = 0xEC,
	PKT_S2C_SpectatorDataChunk = 0xED,
	PKT_S2C_ChangeMissileTarget = 0xEE,
	PKT_S2C_MarkOrSweepForSoftReconnect = 0xEF,
	PKT_S2C_SetShopEnabled = 0xF0,
	PKT_S2C_CreateFollowerObject = 0xF1,
	PKT_S2C_ReattachFollowerObject = 0xF2,
	PKT_S2C_PlayContextualEmote = 0xF3,
	PKT_C2S_PlayContextualEmote = 0xF4,
	PKT_S2C_SetHoverIndicatorTarget = 0xF5,
	PKT_S2C_SetHoverIndicatorEnabled = 0xF6,
	PKT_S2C_SystemMessage = 0xF7,
	PKT_S2C_ChangeEmitterGroup = 0xF8,
	PKT_S2C_UpdateRestrictedChatCount = 0xF9,
	PKT_S2C_TeamBalanceVote = 0xFA,
	PKT_C2S_TeamBalanceVote = 0xFB,
	PKT_S2C_TeamBalanceStatus = 0xFC,
	PKT_S2C_SetItemCharges = 0xFD,
	PKT_CountOfBasicPackets = 0xFE,
	PKT_ExtendedPacket = 0xFE,
	PKT_Batched = 0xFF,
	PKT_SpawnMarkerS2C = 0x100,
	PKT_S2C_UnitSetAutoAttackGroundAllowed = 0x101,
	PKT_S2C_UnitSetShowAutoAttackIndicator = 0x102,
	PKT_S2C_AnimationUpdateTimeStep = 0x103,
	PKT_S2C_UnitSetSpellPARCost = 0x104,
	PKT_S2C_UnitSetDrawPathMode = 0x105,
	PKT_C2S_UnitSendDrawPath = 0x106,
	PKT_S2C_AmmoUpdate = 0x107,
	PKT_S2C_UnitSetCursorReticle = 0x108,
	PKT_NPC_BuffUpdateNumCounter = 0x109,
	PKT_C2S_UndoItemReq = 0x10A,
	PKT_S2C_SetUndoEnabled = 0x10B,
	PKT_S2C_SetInventory = 0x10C,
	PKT_S2C_ChangeMissileSpeed = 0x10D,
	PKT_S2C_SetCanSurrender = 0x10E,
	PKT_S2C_UnitSetLookAt = 0x10F,
	PKT_S2C_DestroyUnit = 0x110,
	PKT_S2C_UnitSetSpellLevelOverrides = 0x111,
	PKT_S2C_UnitSetMaxLevelOverride = 0x112,
	PKT_S2C_UnitSetPARType = 0x113,
	PKT_S2C_MoveMarker = 0x114,
	PKT_ReplayOnly_MultiKillCountUpdate = 0x115,
	PKT_S2C_NeutralMinionTimerUpdate = 0x116,
	PKT_S2C_UpdateDeathTimer = 0x117,
	PKT_S2C_UpdateSpellToggle = 0x118,
	PKT_S2C_UpdateBounceMissile = 0x119,
	PKT_S2C_DebugLogGoldSources = 0x11A,
	PKT_C2S_CheatLogGoldSources = 0x11B,
	PKT_S2C_ShopItemSubstitutionSet = 0x11C,
	PKT_S2C_ShopItemSubstitutionClear = 0x11D,
	PKT_S2C_ResetClient = 0x11E,
	PKT_S2C_IncrementMinionKills = 0x11F,
	PKT_S2C_UpdateAttackSpeedCapOverrides = 0x120,
	PKT_S2C_NotifyContextualSituation = 0x121,
	PKT_S2C_CreateMinionCamp = 0x122,
	PKT_S2C_SpawnTurret = 0x123,
	PKT_S2C_UpdateAscended = 0x124,
	PKT_ChangeSlotSpellData_OwnerOnly = 0x125,
	PKT_Die_MapView = 0x126,
	PKT_SetInventory_MapView = 0x127,
	PKT_MessageToClient_MapView = 0x128,
	PKT_StartSpellTargeter = 0x129,
	PKT_StopSpellTargeter = 0x12A,
	PKT_CameraLock = 0x12B,
	PKT_TeamUpdateDragonBuffCount = 0x12C,
	PKT_SetFadeOut = 0x12D,
	PKT_AddConeRegion = 0x12E,
	PKT_UnlockAnimation = 0x12F,
}`;

let packetObj = packetEnum
	.replace(/PKT_/g, '')
	.replace(/ = /g, ': ');

let packetIdLines = packetObj.split('\n');

let packetNames = [];

packetIdLines = packetIdLines.map(line => {
	if (!line.includes(': '))
		return line;

	let [name, id] = line.split(': ');
	name = name.trim();

	let name2 = name
		.replace('SPM_', '')
		.replace('S2C_', '')
		.replace('C2S_', '')
		.replace('CHAR_', '')
		.replace('NPC_', '')
		.replace('S2C', '')
		.replace('C2S', '')
		.replace('Visiblity', 'Visibility')
		.replace('SendSelectedObjID', 'SendSelectedObjId');

	if (packetNames.includes(name2)) {
		let toAdd = '';
		if (name.includes('S2C'))
			toAdd = 'S2C';
		else if (name.includes('C2S'))
			toAdd = 'C2S';
		name2 += toAdd;
	}

	packetNames.push(name2);
	return `\t${name2}: ${id}`;
});

packetIdLines = packetIdLines.filter(line => {
	return !line.includes('Dummy')
		&& !line.includes('CountOfExtendedPackets')
		&& !line.includes('UpperLimitForPacketIDs');
});

let packetObj2 = packetIdLines.join('\n');
console.log('export default ' + packetObj2 + ';');
