
const PacketIds = require('../Packets/PacketIds');

module.exports = {
	[PacketIds.KEY_CHECK]:								require('./0x00-KEY_CHECK'),
	[PacketIds.C2S_TutorialAudioEventFinished]:			require('./0x05-TutorialAudioEventFinished'),
	[PacketIds.C2S_SynchSimTime]:						require('./0x08-SynchSimTime'),
	[PacketIds.C2S_RemoveItemReq]:						require('./0x09-RemoveItemReq'),
	[PacketIds.BID_ResumePacket]:						require('./0x0A-ResumePacket'),
	[PacketIds.C2S_QueryStatusReq]:						require('./0x14-QueryStatusReq'),
	[PacketIds.C2S_Ping_Load_Info]:						require('./0x16-Ping_Load_Info_'),
	[PacketIds.C2S_WriteNavFlags_Acc]:					require('./0x1D-WriteNavFlags_Acc'),
	[PacketIds.C2S_SwapItemReq]:						require('./0x20-SwapItemReq'),
	[PacketIds.C2S_World_SendCamera_Server]:			require('./0x2E-World_SendCamera_Server'),
	[PacketIds.C2S_UpgradeSpellReq]:					require('./0x39-UpgradeSpellReq'),
	[PacketIds.C2S_UseObject]:							require('./0x3A-UseObject'),
	[PacketIds.C2S_UpdateGameOptions]:					require('./0x47-UpdateGameOptions'),
	[PacketIds.C2S_PlayEmote]:							require('./0x48-PlayEmote'),
	[PacketIds.C2S_PlayVOCommand]:						require('./0x49-PlayVOCommand'),
	[PacketIds.C2S_OnScoreBoardOpened]:					require('./0x4B-OnScoreBoardOpened'),
	[PacketIds.C2S_ClientReady]:						require('./0x52-ClientReady'),
	[PacketIds.C2S_StatsUpdateReq]:						require('./0x56-StatsUpdateReq'),
	[PacketIds.C2S_MapPing]:							require('./0x57-MapPing'),
	[PacketIds.C2S_OnShopOpened]:						require('./0x5D-OnShopOpened'),
	[PacketIds.C2S_RequestJoinTeam]:					require('./0x64-RequestJoinTeam'),
	[PacketIds.C2S_Chat]:								require('./0x68-Chat'),
	[PacketIds.C2S_OnTipEvent]:							require('./0x6D-OnTipEvent'),
	[PacketIds.C2S_IssueOrderReq]:						require('./0x72-IssueOrderReq'),
	[PacketIds.C2S_Waypoint_Acc]:						require('./0x77-Waypoint_Acc'),
	[PacketIds.C2S_World_LockCamera_Server]:			require('./0x81-World_LockCamera_Server'),
	[PacketIds.C2S_BuyItemReq]:							require('./0x82-BuyItemReq'),
	[PacketIds.C2S_ClientFinished]:						require('./0x8D-ClientFinished'),
	[PacketIds.C2S_Exit]:								require('./0x8F-Exit_'),
	[PacketIds.S2C_World_SendGameNumber]:				require('./0x92-World_SendGameNumber'),
	[PacketIds.C2S_CastSpellReq]:						require('./0x9A-CastSpellReq'),
	[PacketIds.C2S_Reconnect]:							require('./0x9C-SoftReconnect'),
	[PacketIds.BID_PausePacket]:						require('./0xA1-PausePacket'),
	[PacketIds.C2S_TeamSurrenderVote]:					require('./0xA4-TeamSurrenderVote'),
	[PacketIds.C2S_OnReplication_Acc]:					require('./0xA8-OnReplication_Acc'),
	[PacketIds.C2S_SendSelectedObjID]:					require('./0xAF-SendSelectedObjId'),
	[PacketIds.C2S_SynchVersion]:						require('./0xBD-SynchVersion'),
	[PacketIds.C2S_CharSelected]:						require('./0xBE-CharSelected'),
	[PacketIds.C2S_OnTutorialPopupClosed]:				require('./0xCC-OnTutorialPopupClosed'),
	[PacketIds.C2S_OnQuestEvent]:						require('./0xCD-OnQuestEvent'),
	[PacketIds.C2S_OnRespawnPointEvent]:				require('./0xD6-OnRespawnPointEvent'),
	[PacketIds.C2S_SpellChargeUpdateReq]:				require('./0xE6-SpellChargeUpdateReq'),
	[PacketIds.C2S_SpectatorDataReq]:					require('./0xEA-SpectatorDataReq'),
	[PacketIds.C2S_PlayContextualEmote]:				require('./0xF4-PlayContextualEmote'),
	[PacketIds.C2S_TeamBalanceVote]:					require('./0xFB-TeamBalanceVote'),
	[PacketIds.C2S_UnitSendDrawPath]: 					require('./0x0106-UnitSendDrawPath'),
	//[PacketIds.C2S_UndoItemReq]: 						require('./0x010A-UndoItemReq'),
	[PacketIds.C2S_CheatLogGoldSources]: 				require('./0x011B-CheatLogGoldSources'),
	0x64:												require('./0x64-RequestJoinTeam'),
	0x68:												require('./0x68-Chat'),
};
